# Generated by Django 5.1.2 on 2025-05-18 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_adquisicion', models.DateField()),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_mantenimiento', 'En Mantenimiento'), ('obsoleto', 'Obsoleto'), ('baja', 'De Baja')], default='activo', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='activos/')),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_creados', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='usuarios.departamento')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['-fecha_adquisicion'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ActivoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('nivel_importancia', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Crítica')], default=2)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.activo')),
            ],
            options={
                'verbose_name': 'Activo en Proceso',
                'verbose_name_plural': 'Activos en Procesos',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('fecha_programada', models.DateField()),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.activo')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('academico', 'Académico'), ('administrativo', 'Administrativo')], max_length=20)),
                ('activos', models.ManyToManyField(through='inventario.ActivoProceso', to='inventario.activo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='usuarios.departamento')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
            },
        ),
        migrations.AddField(
            model_name='activoproceso',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proceso'),
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventario.activo')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('fecha_garantia', models.DateField(blank=True, null=True)),
                ('periodicidad_mantenimiento', models.IntegerField(default=180, help_text='Periodicidad en días')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Hardware',
                'verbose_name_plural': 'Hardware',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventario.activo')),
                ('version', models.CharField(max_length=50)),
                ('tipo_licencia', models.CharField(choices=[('perpetua', 'Perpetua'), ('temporal', 'Temporal'), ('open_source', 'Open Source'), ('freeware', 'Freeware')], max_length=20)),
                ('clave_activacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('numero_licencias', models.IntegerField(default=1)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
            },
        ),
        migrations.AlterUniqueTogether(
            name='activoproceso',
            unique_together={('activo', 'proceso')},
        ),
    ]
