# Generated by Django 5.1.2 on 2025-05-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='software',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
