# Generated by Django 5.1.2 on 2025-05-18 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('aula', 'Aula'), ('sala', 'Sala de Conferencias'), ('oficina', 'Oficina'), ('otro', 'Otro')], max_length=20)),
                ('capacidad', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En Mantenimiento'), ('ocupado', 'Ocupado'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='locales/')),
                ('notas', models.TextField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='usuarios.departamento')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.CreateModel(
            name='EquipamientoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('defectuoso', 'Defectuoso'), ('mantenimiento', 'En Mantenimiento')], default='operativo', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inventario.hardware')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamiento', to='locales.local')),
            ],
            options={
                'verbose_name': 'Equipamiento de Local',
                'verbose_name_plural': 'Equipamientos de Locales',
                'unique_together': {('local', 'hardware')},
            },
        ),
    ]
