# Generated by Django 5.1.2 on 2025-05-19 08:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['nombre'], 'verbose_name': 'Local', 'verbose_name_plural': 'Locales'},
        ),
        migrations.AddField(
            model_name='local',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='local',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 19, 8, 29, 42, 449313, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En Mantenimiento'), ('ocupado', 'Ocupado'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='local',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.CharField(choices=[('laboratorio', 'Laboratorio'), ('aula', 'Aula'), ('sala', 'Sala de Conferencias'), ('oficina', 'Oficina'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('defectuoso', 'Defectuoso'), ('mantenimiento', 'En Mantenimiento')], default='operativo', max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inventario.hardware')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamientos', to='locales.local')),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'verbose_name_plural': 'Equipamientos',
                'unique_together': {('local', 'hardware')},
            },
        ),
        migrations.DeleteModel(
            name='EquipamientoLocal',
        ),
    ]
