# Generated by Django 5.1.2 on 2025-05-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cargo',
        ),
    ]
