# Generated by Django 5.1.2 on 2025-05-18 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuestionarios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel_general', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='diagnostico.cuestionario')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='usuarios.departamento')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('recomendacion', models.TextField(blank=True, null=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='diagnostico.diagnostico')),
            ],
            options={
                'verbose_name': 'Indicador de Diagnóstico',
                'verbose_name_plural': 'Indicadores de Diagnóstico',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('escala', 'Escala (1-5)'), ('si_no', 'Sí/No'), ('texto', 'Texto libre')], max_length=20)),
                ('categoria', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='diagnostico.cuestionario')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.IntegerField(blank=True, null=True)),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='diagnostico.diagnostico')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='diagnostico.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'unique_together': {('diagnostico', 'pregunta')},
            },
        ),
    ]
